# CMake generated Testfile for 
# Source directory: /media/boxuan/Data21/projects/sando_py/sando-core/cpp
# Build directory: /media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(minjerk "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_minjerk" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/minco_cases.txt")
set_tests_properties(minjerk PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;20;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(obstacles "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_obstacles" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/obstacles_cases.txt")
set_tests_properties(obstacles PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;24;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(cost "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_cost" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/cost_cases.txt")
set_tests_properties(cost PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;28;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(localopt "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_localopt" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/localopt_cases.txt")
set_tests_properties(localopt PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;31;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(types "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_types" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/types_cases.txt")
set_tests_properties(types PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;34;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(voxel_map "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_voxel_map" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/voxel_map_cases.txt")
set_tests_properties(voxel_map PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;37;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(local_opt_terms "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_local_opt_terms" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/local_opt_terms_cases.txt")
set_tests_properties(local_opt_terms PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;40;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(voxel_map_helpers "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_voxel_map_helpers" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/voxel_map_helpers_cases.txt")
set_tests_properties(voxel_map_helpers PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;43;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(graph_search "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_graph_search" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/graph_search_cases.txt")
set_tests_properties(graph_search PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;46;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(local_opt_hardalm "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_local_opt_hardalm" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/local_opt_hardalm_cases.txt")
set_tests_properties(local_opt_hardalm PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;49;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(minco_cost_grad "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_minco_cost_grad" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/minco_cost_grad_cases.txt")
set_tests_properties(minco_cost_grad PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;52;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(hgp_planner "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_hgp_planner" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/hgp_planner_cases.txt")
set_tests_properties(hgp_planner PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;55;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(plan_minco "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_plan_minco" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/plan_minco_cases.txt")
set_tests_properties(plan_minco PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;58;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(hgp_manager "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_hgp_manager" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/hgp_manager_cases.txt")
set_tests_properties(hgp_manager PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;61;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(planner "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_planner" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/planner_cases.txt")
set_tests_properties(planner PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;64;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(bspline "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_bspline" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/bspline_cases.txt")
set_tests_properties(bspline PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;67;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(utils_math "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_utils_math" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/utils_math_cases.txt")
set_tests_properties(utils_math PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;70;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(basis_converter "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_basis_converter" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/basis_converter_cases.txt")
set_tests_properties(basis_converter PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;73;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(obstacle_tracker "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_obstacle_tracker" "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/golden/obstacle_tracker_cases.txt")
set_tests_properties(obstacle_tracker PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;76;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
add_test(dyntraj_labelset "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/build_v2/test_dyntraj_labelset")
set_tests_properties(dyntraj_labelset PROPERTIES  _BACKTRACE_TRIPLES "/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;80;add_test;/media/boxuan/Data21/projects/sando_py/sando-core/cpp/CMakeLists.txt;0;")
